# This is a basic workflow to help you get started with Actions

name: Master Linux Kernel Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the ukl branch
  #push:
    #branches: [ ukl-5.14 ]
  #pull_request:
    #branches: [ ukl-5.14 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
            
      #Checkout Linux repo  Master branch    
      - name: checkout Linux Repo Master Branch
        uses: actions/checkout@v2
        with:
            ref: master 

      # Installs required packages
      - name: Install requirements
        run: sudo apt-get install build-essential flex bison libelf-dev libssl-dev
        
      # Create Linux Config File
      - name: Build Kernel
        run: make defconfig 

      # Build the kernel
      - name: Build Kernel
        run: make all
