# This workflow builds the UKL Kernel from Scratch, Boots it in QEMU, and runs unit tests

name: MEMCACHED_TEST

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the ukl-5.14 branch
#   push:
#     branches: [ ukl-5.14 ]
#   pull_request:
#     branches: [ ukl-5.14 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  #Boot Test Job
  Memcached:
  
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
          
      #Checkout UKL/Linux repo - branch 5.14      
      - name: checkout Linux UKL Repo
        uses: actions/checkout@v2
        with:
            path: linux
    
      #Clone Repos  
      - name: Clone Dependency Repos
        uses: ./linux/.github/workflows/composite/clone
        with: 
          ukl_token: ${{ secrets.ukl_token }}
          
#       # Turn On AfterSpace Configuration Option
#       - name: Update Config Options
#         run: |
#             cd ./ukl/tests
#             cat linux_config > linux_config_permute
#             cp linux_config_permute ../Linux-Configs/ukl/golden_config-5.7-broadcom
      
      # Turn On AfterSpace Configuration Option
      - name: Install Memcached Tools
        run: |
            sudo apt-get install automake libtool libevent-dev
      
      #To-Do - Installations
      
            # Turn On AfterSpace Configuration Option
      - name: Install libmemcached
        run: |
            cd ./ukl/tests/memcached
            tar xvzf libmemcached-1.0.18.tar.gz
            cp ./memflush.cc ./libmemcached-1.0.18/clients/
            cp ./Makefile.in ./libmemcached-1.0.18
            cd libmemcached-1.0.18
            ./configure --enable-memaslap
            sudo make install 
          
#       # Runs Make All to build the UKL
#       - name: Compile UKL
#         run: |
#           cd ukl/
#           make all
      
#       #Run Boot Test
#       - name: Run UKL Boot Test
#         run: |
#           cd ukl/tests
#           ./run_boot.sh
      
      #Move Linux back to Parent Directory to enable default action cleanup
      - name: Prepare for Cleanup
        if: always()
        run: | 
          mv ukl/linux .


      
