# This workflow builds the UKL Kernel from Scratch, Boots it in QEMU, and runs unit tests

name: UKL UNIT TESTS

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the ukl-5.14 branch
#   push:
#     branches: [ ukl-5.14 ]
#   pull_request:
#     branches: [ ukl-5.14 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  #Test Turning all UKL Config Options On
  TEST_ALL_UKL_OPTIONS_ENABLED:
  
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
          
      #Checkout UKL/Linux repo - branch 5.14      
      - name: checkout Linux UKL Repo
        uses: actions/checkout@v2
        with:
            path: linux
    
      #Clone Repos  
      - name: Clone Dependency Repos
        uses: ./linux/.github/workflows/composite/clone
        with: 
          ukl_token: ${{ secrets.ukl_token }}
      
      #=====================================
      #Insert Step to Turn on All Flags Here
      #=====================================
      # Runs Make All to build the UKL
      - name: Compile UKL
        run: |
          cd ukl/
          make all
      
      #Test Config with Mybench Small Tests
      - name: Test Config with MyBench Small Unit Tests
        run: |
          cd ukl/tests
          ./run_mybench_small.sh
      
      #Move Linux back to Parent Directory to enable default action cleanup
      - name: Prepare for Cleanup
        run: | 
          mv ukl/linux .

  #Test Another Config
  ANOTHER-CONFIG:
  
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
          
      #Checkout UKL/Linux repo - branch 5.14      
      - name: checkout Linux UKL Repo
        uses: actions/checkout@v2
        with:
            path: linux
    
      #Clone Repos  
      - name: Clone Dependency Repos
        uses: ./linux/.github/workflows/composite/clone
        with: 
          ukl_token: ${{ secrets.ukl_token }}
      
      #=====================================
      #Insert Step to Turn on All Flags Here
      #=====================================
      # Runs Make All to build the UKL
      - name: Compile UKL
        run: |
          cd ukl/
          make all
      
      #Test Config with Mybench Small Tests
      - name: Test Config with MyBench Small Unit Tests
        run: |
          cd ukl/tests
          ./run_mybench_small.sh
      
      #Move Linux back to Parent Directory to enable default action cleanup
      - name: Prepare for Cleanup
        run: | 
          mv ukl/linux .
