# This workflow builds the UKL Kernel from Scratch, Boots it in QEMU, and runs unit tests

name: UKL UNIT TESTS

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the ukl-5.14 branch
  push:
    branches: [ ukl-5.14 ]
  pull_request:
    branches: [ ukl-5.14 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  #Boot Test Job
  Boot-Test:
  
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
          
      #Checkout UKL/Linux repo - branch 5.14      
      - name: checkout Linux UKL Repo
        uses: actions/checkout@v2
        with:
            path: linux
    
      #Clone Repos  
      - name: Clone Dependency Repos
        uses: ./linux/.github/workflows/composite/clone
        with: 
          ukl_token: ${{ secrets.ukl_token }}
          
      # Runs Make All to build the UKL
      - name: Compile UKL
        run: |
          cd ukl/
          make all
      
      #Run Boot Test
      - name: Run UKL Boot Test
        run: |
          cd ukl/tests
          ./run_boot.sh
      
      #Move Linux back to Parent Directory to enable default action cleanup
      - name: Prepare for Cleanup
        if: always()
        run: | 
          mv ukl/linux .

  #Run LM Bench System Calls Tests
  LMBench_SysCalls_Tests:
  
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
          
      #Checkout UKL/Linux repo - branch 5.14      
      - name: checkout Linux UKL Repo
        uses: actions/checkout@v2
        with:
            path: linux
    
      #Clone Repos  
      - name: Clone Dependency Repos
        uses: ./linux/.github/workflows/composite/clone
        with: 
          ukl_token: ${{ secrets.ukl_token }}
          
      # Runs Make All to build the UKL
      - name: Compile UKL
        run: |
          cd ukl/
          make all
      
      #Run LM Bench Sys Calls Tests
      - name: Run LM Bench Sys Calls tests
        run: |
          cd ukl/tests
          ./run_lmbench_syscalls.sh
          
      #Move Linux back to Parent Directory to enable default action cleanup
      - name: Prepare for Cleanup
        if: always()
        run: | 
          mv ukl/linux .
      
