# This workflow builds the UKL Kernel from Scratch, Boots it in QEMU, and runs unit tests

name: UKL CLONE REPOS

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the ukl-5.14 branch
#   push:
#     branches: [ ukl-5.14 ]
#   pull_request:
#     branches: [ ukl-5.14 ]

  # Allows Action to be Reused in Other Actions
  workflow_call:
#       secrets:
#         ukl_token:
#           required: true

jobs:
  # This workflow contains a single job called "build"
  clone_repos:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
          
      #Checkout UKL/Linux repo - branch 5.14      
      - name: checkout Linux UKL Repo
        uses: actions/checkout@v2
        with:
            path: linux
    
      # Checks-out Makefile from UKL repo
      - name: Checkout MakeFile
        uses: actions/checkout@v2
        with:
          repository: whunt1965/ukl
          token: ${{ secrets.ukl_token }}
          ref: terminate-qemu
          path: ukl
    
      #Copy the Linux Directory into the UKL directory
      - name: Copy Linux dir into ukl dir
        run: |
          mv /home/runner/work/linux/linux/linux ukl/
          cd ukl
    
      
      #Checkout Linux-Configs repo
      - name: checkout config file
        uses: actions/checkout@v2
        with:
            repository: whunt1965/Linux-Configs
            ref: master
            token: ${{ secrets.ukl_token }}
            path: ukl/Linux-Configs
            
            
      #Checkout gcc repo - branch releases/gcc-9.3.0     
      - name: checkout GCC repo
        uses: actions/checkout@v2
        with:
            repository: gcc-mirror/gcc
            ref: releases/gcc-9.3.0
            path: ukl/gcc
            
      #Checkout UKL/glibc repo - branch ukl   
      - name: checkout glibc repo
        uses: actions/checkout@v2
        with:
            repository: unikernelLinux/glibc
            ref: ukl
            token: ${{ secrets.ukl_token }}
            path: ukl/glibc
            
      #Checkout min-initrd repo - branch ukl   
      - name: checkout min-initrd repo
        uses: actions/checkout@v2
        with:
            repository: whunt1965/min-initrd
            ref: qemu-terminate
            token: ${{ secrets.ukl_token }}
            path: ukl/min-initrd

      # Installs required packages for build
      - name: Update and install package requirements
        run: |
          sudo apt-get update
          sudo apt-get install git build-essential flex bison supermin libelf-dev libssl-dev texinfo libgmp3-dev libmpc-dev libmpfr-dev qemu-kvm
      
